In [1]:
#1.Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.
#Expected Output:
#Original List: [12.23, 13.32, 100, 36.32] One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]

import numpy as np

original_list = [12.23, 13.32, 100, 36.32]

array = np.array(original_list)

print("Original List:", original_list)
print("One-dimensional NumPy array:", array)


Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array: [ 12.23  13.32 100.    36.32]


In [2]:
#2.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
#Expected Output:
#[[ 2 3 4] [ 5 6 7] [ 8 9 10]]

import numpy as np

matrix = np.arange(2, 11).reshape(3, 3)

print(matrix)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [3]:
#3.Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.
#[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#Update sixth value to 11 [ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

import numpy as np

vector = np.zeros(10)
print("Original vector:", vector)

vector[6] = 11

print("Updated vector:", vector)


Original vector: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Updated vector: [ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [4]:
#4.Write a NumPy program to create an array with values ranging from 12 to 38.
#Expected Output:
#[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
import numpy as np

array = np.arange(12, 38)

print(array)


[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [5]:
#5.Write a NumPy program to convert an array to a floating type.
#Sample output:
#Original array [1, 2, 3, 4]

import numpy as np
original_array = np.array([1, 2, 3, 4])
print("Original array:", original_array)
float_array = original_array.astype(float)
print("Converted to float:", float_array)


Original array: [1 2 3 4]
Converted to float: [1. 2. 3. 4.]


In [6]:
#6.Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array.
#Sample Array [0, 12, 45.21, 34, 99.91] [-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]
#Expected Output:
#Values in Fahrenheit degrees: [ 0. 12. 45.21 34. 99.91 32. ]
#Values in Centigrade degrees: [-17.78 -11.11 7.34 1.11 37.73 0. ]
#Values in Centigrade degrees: [-17.78 -11.11 7.34 1.11 37.73 0. ]
#Values in Fahrenheit degrees: [-0. 12. 45.21 34. 99.91 32. ]

import numpy as np

centigrade_values = np.array([-17.78, -11.11, 7.34, 1.11, 37.73, 0.])

fahrenheit_values = centigrade_values * 9 / 5 + 32

print("Values in Centigrade degrees:", centigrade_values)
print("Values in Fahrenheit degrees:", fahrenheit_values)


Values in Centigrade degrees: [-17.78 -11.11   7.34   1.11  37.73   0.  ]
Values in Fahrenheit degrees: [-4.0000e-03  1.2002e+01  4.5212e+01  3.3998e+01  9.9914e+01  3.2000e+01]


In [7]:
#7.Write a NumPy program to append values to the end of an array.
#Expected Output:
#Original array: [10, 20, 30]
#After append values to the end of the array: [10 20 30 40 50 60 70 80 90]

import numpy as np

original_array = np.array([10, 20, 30])
print("Original array:", original_array)

values_to_append = [40, 50, 60, 70, 80, 90]

updated_array = np.append(original_array, values_to_append)
print("After append values to the end of the array:", updated_array)


Original array: [10 20 30]
After append values to the end of the array: [10 20 30 40 50 60 70 80 90]


In [8]:
#8.Create a random NumPy array of 10 elements and calculate the mean, median, and standard deviation of the array.
import numpy as np

random_array = np.random.rand(10) * 100  # Random values between 0 and 100

mean_value = np.mean(random_array)
median_value = np.median(random_array)
std_deviation = np.std(random_array)

print("Random Array:", random_array)
print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_deviation)


Random Array: [16.42250417 43.16148847 50.67175325 69.35358025 59.30335093 70.74147939
 12.63295474 87.25332357 75.69591434 75.9994732 ]
Mean: 56.12358223112866
Median: 64.32846559028633
Standard Deviation: 24.106769398562587


In [10]:
#9.Create a 10x10 array with random values and find the minimum and maximum values.
import numpy as np

random_array = np.random.rand(10, 10)

min_value = np.min(random_array)
max_value = np.max(random_array)

print("Random 10x10 Array:\n", random_array)
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)


Random 10x10 Array:
 [[0.75966992 0.2958067  0.27787937 0.82493036 0.82729235 0.86043613
  0.34329554 0.57731567 0.73487571 0.59751147]
 [0.84401248 0.43768926 0.5549774  0.53792832 0.16733106 0.60396041
  0.77700812 0.83414265 0.85366133 0.5966634 ]
 [0.36726518 0.06133022 0.80521116 0.55817856 0.77501382 0.15084464
  0.17455797 0.97045556 0.17630072 0.8913508 ]
 [0.13112853 0.05165068 0.29004462 0.23059228 0.20785016 0.02366888
  0.09324091 0.55970287 0.22032261 0.38009678]
 [0.98525271 0.54542148 0.89638723 0.63726948 0.44765257 0.85641439
  0.94129318 0.59113609 0.42980025 0.76313593]
 [0.68194893 0.34966422 0.28177412 0.78703504 0.58305027 0.58552067
  0.79751074 0.41006691 0.05639091 0.98381067]
 [0.72901671 0.40151029 0.65554296 0.70662053 0.04579712 0.58375042
  0.46901199 0.32748026 0.16329639 0.8063214 ]
 [0.76042673 0.42144937 0.31866096 0.6740841  0.48924384 0.36703321
  0.83458304 0.75509836 0.11840681 0.5399306 ]
 [0.73651584 0.3242794  0.25148728 0.79131491 0.69415399 0.

In [11]:
#10.Create a 3x3x3 array with random values.
import numpy as np
random_array = np.random.rand(3, 3, 3)

print("3x3x3 Random Array:\n", random_array)


3x3x3 Random Array:
 [[[0.84249121 0.93079072 0.57063241]
  [0.20314356 0.23678221 0.96368336]
  [0.24690599 0.75129684 0.2150303 ]]

 [[0.57586642 0.13852221 0.22479387]
  [0.86417993 0.68076951 0.60673504]
  [0.18806847 0.6949056  0.61306187]]

 [[0.51469228 0.67759028 0.61606845]
  [0.99856448 0.48219093 0.95639517]
  [0.75471781 0.97686628 0.31450228]]]
